blank_issues_enabled: false
contact_links:
  - name: GitHub Discussion
    url: https://github.com/Stijnman/stock-intelligence-engine/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: mailto:security@stijnman.com
    about: Please report security vulnerabilities here.
